version: '3'

services:
  similar-ten-webapp:
    image: similar-ten-webapp
    # restart: always
    build:
      context: ./src/web/similarTen
    container_name: similarTen-webapp-c
    ports:
      - "5000:5003"
    volumes:
      - ./src/dataset:/app/dataset
      - ./src/web/similarTen:/app

